name: Release
on:
  pull_request:
    branches:
      - dev
      - dev*
      - master
    types:
      - closed
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: |
          git fetch --prune --unshallow --tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Set up Git user
        run: |
          git config --local user.name ${{ github.repository_owner }}_action_bot
          git config --local user.email ${{ github.repository_owner }}@users.noreply.github.com

      - name: Bump Version and Create Tag
        id: create_tag
        run: |
          python -m pip install pep440
          if [[ "${{ github.event.pull_request.base.ref }}" == dev* ]] ; then
            echo "| Dev branch: ${{ github.event.pull_request.base.ref }}"
            if [[ "${{ github.event.pull_request.title }}" == minor:* ]] ; then
              python ./tools/set_version_3div.py -b minor -r stable
            elif [[ "${{ github.event.pull_request.title }}" == skip-version:* ]] ; then
              python ./tools/set_version_3div.py -b skip -r stable
            else 
              python ./tools/set_version_3div.py -b patch -r stable
            fi
          elif [[ "${{ github.event.pull_request.base.ref }}" == master ]] ; then
            echo "| Master branch: ${{ github.event.pull_request.base.ref }}"
            if [[ "${{ github.event.pull_request.title }}" == major:* ]] ; then
              python ./tools/set_version_3div.py -b major -r stable
            elif [[ "${{ github.event.pull_request.title }}" == skip-version:* ]] ; then
              python ./tools/set_version_3div.py -b skip -r stable
            else 
              python ./tools/set_version_3div.py -b minor -r stable
            fi
          else
            echo "| Invalid branch: ${{ github.event.pull_request.base.ref }}"
            echo "| Exiting..."
            exit 1
          fi

      - name: Push Version Change
        if: (!contains(github.event.pull_request.title, 'skip-version:'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add qurrium_qua_libs/VERSION.txt
          git commit -m "chore(version): update version to ${{ steps.create_tag.outputs.VERSION }}"
          git push origin

      - name: Check out Version
        run: |
          echo "| Version: ${{ steps.create_tag.outputs.VERSION }} in action"
          echo "| Tag exists: ${{ steps.create_tag.outputs.exists }}"

      - name: Create Version Tag
        if: (!contains(github.event.pull_request.title, 'skip-version:'))
        run: |
          if ${{ steps.create_tag.outputs.exists }} ; then
            echo "| Tag exists, skipped add"
          else 
            echo "| Tag doesn't exist, adding tag"
            git tag -a ${{ steps.create_tag.outputs.VERSION }} -m "chore(version): update version to ${{ steps.create_tag.outputs.VERSION }}"
            git push origin ${{ steps.create_tag.outputs.VERSION }}
          fi
