---
name: Wheel Builds
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Reversion
        id: reversion
        run: |
          python -m pip install pep440
          python ./tools/set_version_3div.py

      # Build wheels
      - name: Build wheels
        run: |
          python -m pip install --upgrade pip setuptools wheel pipx
          python -m pipx run build

      # Upload the wheelhouse as an artifact
      - name: Distribute Upload
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz
          name: shared-wheel-builds

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build_wheels

    steps:
      - uses: actions/checkout@v4
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: shared-wheel-builds

      - name: Set release variables
        id: set_release_vars
        run: |
          echo "release_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "release_body=update" >> $GITHUB_OUTPUT
          echo "prerelease=false" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{steps.set_release_vars.outputs.release_name}}
          body: |
            ${{steps.set_release_vars.outputs.release_body}}
          prerelease: ${{steps.set_release_vars.outputs.prerelease}}
          draft: true
          generate_release_notes: true
          files: |
            qurrium_qua_libs-${{ github.ref_name }}-py3-none-any.whl
            qurrium_qua_libs-${{ github.ref_name }}.tar.gz
